[package]
name = "common"
version = "0.1.0"
edition = "2024"

[features]
default = ["napi"]
napi = []

[dependencies]
oxc_span = { workspace = true }
oxc_ast = { workspace = true }
oxc_allocator = { workspace = true }
oxc_semantic = { workspace = true }
oxc_parser = { workspace = true }
oxc_ast_visit = { workspace = true }

napi-derive = { workspace = true }
napi = { workspace = true }
phf = { workspace = true }
indexmap = { workspace = true }
html-escape = { workspace = true }
